# Generated by Django 4.2.20 on 2025-03-24 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
        ('accounts', '0003_alter_profile_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.chapter'),
        ),
        migrations.AddField(
            model_name='profile',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.game'),
        ),
    ]
