# Generated by Django 4.2.20 on 2025-04-07 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_chapter_profile_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='rank',
            field=models.CharField(choices=[('bronze', 'خاموشی'), ('silver', 'ادراک'), ('gold', 'چالشگر'), ('platinum', 'همنشین'), ('diamond', 'ادغامیافته')], default=('bronze', 'خاموشی'), max_length=255),
        ),
    ]
