# Generated by Django 4.2.20 on 2025-04-11 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_profile_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='rank',
            field=models.CharField(choices=[('خاموشی', 'خاموشی'), ('ادراک', 'ادراک'), ('چالشگر', 'چالشگر'), ('همنشین', 'همنشین'), ('ادغامیافته', 'ادغامیافته')], default='خاموشی', max_length=255),
        ),
    ]
